### ISSUE TITLE
Which release has capability to write/send to CAN-bus?

### ISSUE THREAD

**Issue by flapse** [commaai/panda-artifacts#1]
Hi,

I have a white panda, and are trying to execute the python files from the example folder. George is showing on his periscope video (https://www.pscp.tv/comma_ai/1OyKArVVOALGb) how he queries the bus and can request data (query_vin_and_stats.py from example folder). He mentions that only development (DEV) firmware can write CAN messages or you should build your own firmware.

In this repository are all the releases. Some have "DEV" mentioned in the file name. Some have "RELEASE" mentioned in their filename. Some have both. My question: Do the firmware files with "DEV" have the output (all outputs) enabled? Can you write to the CAN bus with does firmwares?

If not, is there either a firmware available that does have the capability to write to the CAN bus? Or alternatively is their a guide how to compile your firmware yourself, and which compiler settings to do to enable the outputs?

Hope you can help me in the right direction!?

Kind regards,

Flapse

**Comment by robbederks** [comment]
All firmwares in this repo are indeed RELEASE builds which do not have the ALLOUTPUT capability.
Depending on what you want to do, this might not be necessary though, you can still send a limited subset of can messages in release firmwares.

For compiling a dev build, please check out the regular commaai/panda repo.

**Comment by flapse** [comment]
Thanks for your quick reply.

What subset of CAN messages can I send with the release firmware? I am trying the example "query_vin_and_stats.py" and that does stalls after the request form vin number has been sent ("isotp_send(panda, b"\x09\x02", 0x7df, recvaddr=0x7df)" )

I am also looking into compilation of the firmware. Is it only the line of current safety mode in safety.h (line 43) file that I have to alter to get ALLOUTPUT?:

//uint16_t current_safety_mode = SAFETY_SILENT;
uint16_t current_safety_mode = SAFETY_ALLOUTPUT;

I am running onto some errors:

```
scons: Reading SConscript files ...
AttributeError: _RSAobj object has no 'size_in_bits' attribute:
  File "/home/michiel/Documenten/Kangoo/CAN/commaai/github/panda/SConstruct", line 5:
    SConscript('board/SConscript')
  File "/usr/lib/python3/dist-packages/SCons/Script/SConscript.py", line 661:
    return method(*args, **kw)
  File "/usr/lib/python3/dist-packages/SCons/Script/SConscript.py", line 598:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/python3/dist-packages/SCons/Script/SConscript.py", line 287:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/home/michiel/Documenten/Kangoo/CAN/commaai/github/panda/board/SConscript", line 133:
    certs = [get_key_header(n) for n in ["debug", "release"]]
  File "/home/michiel/Documenten/Kangoo/CAN/commaai/github/panda/board/SConscript", line 133:
    certs = [get_key_header(n) for n in ["debug", "release"]]
  File "/home/michiel/Documenten/Kangoo/CAN/commaai/github/panda/board/SConscript", line 110:
    assert(rsa.size_in_bits() == 1024)
  File "/home/michiel/.local/lib/python3.9/site-packages/Crypto/PublicKey/RSA.py", line 126:
    raise AttributeError("%s object has no %r attribute" % (self.__class__.__name__, attrname,))
```

**Comment by flapse** [comment]
oeps compilation error solved, just required sudo to compile!

**Comment by flapse** [comment]
the command:
>  sudo ./build_all.sh 
did it! The compilation was sucesfull. 

Now next step: how to make a release zip file that I can upload to the white panda?

In the folder /panda/release is the script "make_release.sh". However the git repository does not include the folder "../../pandaextra" . How do I construct the zip file (release file?) that can be uploaded to the panda?

**Comment by flapse** [comment]
follow up (for those that found this info, and could be useful to learn from my struggle :-)  ):

turns out there is a script flash.sh that is the board-folder. This script uploads your freshly compiled binary file (obj/panda.bin
.signed) to the panda.

This also requires you to use sudo.

And perhaps also important to say: use the boot-button on your panda-paw board (see: https://github.com/commaai/panda/blob/memcpy32/docs/guide.pdf) to bring your panda in programming-mode (press boot-button while powering on your panda).

Still I am not sure which compile options or changes in the code I have to make to be able to control all outputs of the panda. Any tips/hints?
